services:
  wordpress:
    build: .
    ports:
      - 80:80
      - 443:443
    user: 1000:1000
    volumes:
      - .:/var/www/html
    restart: always
    depends_on:
      - database
  database:
    image: mariadb:11.1.2-jammy
    ports:
      - 3306:3306
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: wordpress
    restart: always
    volumes:
      - database:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin
    ports:
      - 8080:80
    environment:
      PMA_HOST: database
      PMA_PORT: 3306
      PMA_DATABASE: wordpress
      PMA_USER: root
      PMA_PASSWORD:
    restart: always
    depends_on:
      - database
volumes:
  database: