name: Composer Normalize

on:
  push:

jobs:
  normalize:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'
          tools: composer-normalize:2

      - name: Composer normalize
        run: composer-normalize --dry-run